// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const metaFuturaBuilding5 = new Entity("Meta futura Building")
engine.addEntity(metaFuturaBuilding5)
const metaFuturaBuilding5transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
metaFuturaBuilding5.addComponentOrReplace(metaFuturaBuilding5transform)
const metaFuturaBuilding5GLTFShape = new GLTFShape("models/MF_Building/Meta futura Building.glb")
metaFuturaBuilding5GLTFShape.withCollisions = true
metaFuturaBuilding5GLTFShape.isPointerBlocker = true
metaFuturaBuilding5GLTFShape.visible = true
metaFuturaBuilding5.addComponentOrReplace(metaFuturaBuilding5GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const metaFuturaOnlyType6 = new Entity("Meta Futura Only Type")
engine.addEntity(metaFuturaOnlyType6)
const metaFuturaOnlyType6transform = new Transform({
  position: new Vector3(8.117737, 5.735278, 0.5484877),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.87096, 2.87096, 2.87096)
})
metaFuturaOnlyType6.addComponentOrReplace(metaFuturaOnlyType6transform)
const metaFuturaOnlyType6GLTFShape = new GLTFShape("models/MF_Logo/Meta Futura Only Type.glb")
metaFuturaOnlyType6GLTFShape.withCollisions = true
metaFuturaOnlyType6GLTFShape.isPointerBlocker = true
metaFuturaOnlyType6GLTFShape.visible = true
metaFuturaOnlyType6.addComponentOrReplace(metaFuturaOnlyType6GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const metaFuturaLightSphere7 = new Entity("Meta futura Light Sphere")
engine.addEntity(metaFuturaLightSphere7)
const metaFuturaLightSphere7transform = new Transform({
  position: new Vector3(8.170889, 16.03464, 5.562241),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5.771701, 5.771701, 5.771701)
})
metaFuturaLightSphere7.addComponentOrReplace(metaFuturaLightSphere7transform)
const metaFuturaLightSphere7GLTFShape = new GLTFShape("models/MF_Lightsphere/Meta futura Light Sphere.glb")
metaFuturaLightSphere7GLTFShape.withCollisions = true
metaFuturaLightSphere7GLTFShape.isPointerBlocker = true
metaFuturaLightSphere7GLTFShape.visible = true
metaFuturaLightSphere7.addComponentOrReplace(metaFuturaLightSphere7GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const mfLogoObject8 = new Entity("MF Logo Object")
engine.addEntity(mfLogoObject8)
const mfLogoObject8transform = new Transform({
  position: new Vector3(7.861102, 8.254826, 0.103693),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.6739925, 0.6739925, 0.6739925)
})
mfLogoObject8.addComponentOrReplace(mfLogoObject8transform)
const mfLogoObject8GLTFShape = new GLTFShape("models/MF_Logo_object/MF Logo Object.glb")
mfLogoObject8GLTFShape.withCollisions = true
mfLogoObject8GLTFShape.isPointerBlocker = true
mfLogoObject8GLTFShape.visible = true
mfLogoObject8.addComponentOrReplace(mfLogoObject8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

